version: 2
jobs:
  build:
    branches:
      only:
        - master
        - merge

    docker:
      - image: ahughes12/popcorn-base:latest

    environment:
      COMPILATION_LOGS: /tmp/compilation_logs

    steps:
      - checkout

      - run: mkdir -p $COMPILATION_LOGS

      - run:
          name: Build arm64
          command: |
            set +o pipefail
            make -j2 defconfig 2>&1 | tee $COMPILATION_LOGS/arm64.log
            make -j2 2>&1 | tee $COMPILATION_LOGS/arm64.log
          environment:
            ARCH: arm64
            CROSS_COMPILE: aarch64-linux-gnu-

      - run:
          name: Build x86_64
          command: |
            set +o pipefail
            cp kernel/popcorn/configs/config-x86_64-qemu .config
            make -j2 2>&1 | tee $COMPILATION_LOGS/x86_64.log

      - run:
          name: Build x86_64_gcc_4_8
          command: |
            set +o pipefail
            update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 60
            cp kernel/popcorn/configs/config-x86_64-qemu .config
            make -j2 2>&1 | tee $COMPILATION_LOGS/x86_64.log

      - run:
          name: Build x86_64_gcc_9
          command: |
            set +o pipefail
            update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60
            cp kernel/popcorn/configs/config-x86_64-qemu .config
            make -j2 2>&1 | tee $COMPILATION_LOGS/x86_64.log

      - store_artifacts:
          path: /tmp/compilation_logs
          destination: raw-test-output
